# Generated by Django 5.2.7 on 2025-10-24 16:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Firm',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('activity', models.TextField(max_length=150)),
                ('address', models.CharField(max_length=100)),
                ('link', models.URLField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vacancy_initial_source', models.CharField(choices=[('SuperJob', 'SuperJob'), ('HH', 'hh.ru')], default='SuperJob')),
                ('title', models.CharField(max_length=100)),
                ('duties', models.TextField(max_length=500)),
                ('requirements', models.TextField(max_length=500)),
                ('payment_from', models.PositiveIntegerField()),
                ('payment_to', models.PositiveIntegerField()),
                ('experience', models.CharField(choices=[('No exp', 'Без опыта'), ('Year', 'От 1 года'), ('Three years', 'От 3 лет'), ('Six years', 'От 6 лет')], default='No exp')),
                ('education', models.CharField(choices=[('Student', 'Учащийся'), ('Higher', 'Высшее образование'), ('Incomplete_higher', 'Неполное высшее'), ('Secondary_special', 'Средне-специальное'), ('Secondary', 'Среднее')], default='Student')),
                ('place_of_work', models.CharField(choices=[('Remote', 'Удаленная'), ('Office', 'Очная')], default='Remote')),
                ('vacancy_valid_until', models.DateTimeField()),
                ('vacancy_url', models.URLField(max_length=150)),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancies.firm')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
