# Generated by Django 5.2.7 on 2025-10-24 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancy',
            options={'verbose_name_plural': 'Vacancies'},
        ),
        migrations.AddField(
            model_name='vacancy',
            name='working_conditions',
            field=models.TextField(default='-', max_length=850, verbose_name='Условия работы'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='firm',
            name='activity',
            field=models.TextField(max_length=150, verbose_name='Род деятельности'),
        ),
        migrations.AlterField(
            model_name='firm',
            name='address',
            field=models.CharField(max_length=100, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='firm',
            name='link',
            field=models.URLField(max_length=50, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='firm',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='duties',
            field=models.TextField(max_length=850, verbose_name='Задачи'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='education',
            field=models.CharField(choices=[('Student', 'Учащийся'), ('Higher', 'Высшее образование'), ('Incomplete_higher', 'Неполное высшее'), ('Secondary_special', 'Средне-специальное'), ('Secondary', 'Среднее')], default='Student', verbose_name='Образование'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='experience',
            field=models.CharField(choices=[('No exp', 'Без опыта'), ('Year', 'От 1 года'), ('Three years', 'От 3 лет'), ('Six years', 'От 6 лет')], default='No exp', verbose_name='Опыт'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='payment_from',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Зп от'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='payment_to',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Зп до'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='place_of_work',
            field=models.CharField(choices=[('Remote', 'Удаленная'), ('Office', 'Очная')], default='Remote', verbose_name='Тип работы'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='requirements',
            field=models.TextField(max_length=850, verbose_name='Требования'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='vacancy_initial_source',
            field=models.CharField(choices=[('SuperJob', 'SuperJob'), ('HH', 'hh.ru')], default='SuperJob', verbose_name='Источник'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='vacancy_valid_until',
            field=models.DateTimeField(verbose_name='Вакансия действительна до'),
        ),
    ]
