# Generated by Django 5.2.7 on 2025-10-24 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0002_alter_vacancy_options_vacancy_working_conditions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='date_added',
            field=models.DateTimeField(auto_now=True, verbose_name='Время добавления'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='vacancy_url',
            field=models.URLField(max_length=150, verbose_name='Ссылка на вакансию'),
        ),
    ]
