# Generated by Django 5.2.7 on 2025-10-26 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0004_searchhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='place_of_work',
            field=models.CharField(choices=[('Office', 'Очная'), ('Remote', 'Удаленная')], default='Office', verbose_name='Тип работы'),
        ),
    ]
