# Generated by Django 5.2.7 on 2025-10-26 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0005_alter_vacancy_place_of_work'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='working_conditions',
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='duties',
            field=models.TextField(max_length=1500, verbose_name='Задачи'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='requirements',
            field=models.TextField(max_length=2000, verbose_name='Требования'),
        ),
    ]
