# Generated by Django 5.2.7 on 2025-10-27 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0007_searchhistory_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='external_vacancy_id',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
