# Generated by Django 5.2.7 on 2025-10-27 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0008_vacancy_external_vacancy_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancy',
            old_name='external_vacancy_id',
            new_name='external_id',
        ),
        migrations.RenameField(
            model_name='vacancy',
            old_name='vacancy_initial_source',
            new_name='initial_source',
        ),
        migrations.RenameField(
            model_name='vacancy',
            old_name='vacancy_url',
            new_name='original_link',
        ),
        migrations.RenameField(
            model_name='vacancy',
            old_name='vacancy_valid_until',
            new_name='valid_until',
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='education',
            field=models.CharField(choices=[('Student', 'Учащийся'), ('Higher', 'Высшее'), ('Incomplete_higher', 'Неполное высшее'), ('Secondary_special', 'Средне-специальное'), ('Secondary', 'Среднее')], default='Student', verbose_name='Образование'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='place_of_work',
            field=models.CharField(choices=[('office', 'Очная'), ('remote', 'Удаленная'), ('not specified', 'Не имеет значения')], default='office', verbose_name='Тип работы'),
        ),
    ]
