# Generated by Django 5.2.7 on 2025-10-27 16:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0009_rename_external_vacancy_id_vacancy_external_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='valid_until',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Вакансия действительна до'),
        ),
    ]
