# Generated by Django 5.2.7 on 2025-10-27 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0010_alter_vacancy_valid_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='firm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vacancies.firm'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='valid_until',
            field=models.DateTimeField(verbose_name='Вакансия действительна до'),
        ),
    ]
