# Generated by Django 5.2.7 on 2025-10-29 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0011_alter_vacancy_firm_alter_vacancy_valid_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='education',
            field=models.CharField(choices=[('not specified', 'Не имеет значения'), ('Student', 'Учащийся'), ('Higher', 'Высшее'), ('Incomplete_higher', 'Неполное высшее'), ('Secondary_special', 'Средне-специальное'), ('Secondary', 'Среднее')], default='not specified', verbose_name='Образование'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='place_of_work',
            field=models.CharField(choices=[('office', 'Очная'), ('remote', 'Удалённая'), ('not specified', 'Не имеет значения')], default='office', verbose_name='Тип работы'),
        ),
    ]
