# Generated by Django 5.2.7 on 2025-10-29 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0012_alter_vacancy_education_alter_vacancy_place_of_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='external_id',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
