# Generated by Django 5.2.7 on 2025-11-03 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0013_alter_vacancy_external_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='currency',
            field=models.CharField(default='RUR', max_length=3, verbose_name='Валюта'),
            preserve_default=False,
        ),
    ]
