# Generated by Django 5.2.7 on 2025-11-10 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0015_alter_vacancy_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='working_conditions',
            field=models.TextField(default='Empty', max_length=1500, verbose_name='Условия работы'),
            preserve_default=False,
        ),
    ]
