# Generated by Django 5.2.7 on 2025-11-12 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0016_vacancy_working_conditions'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
