# Generated by Django 5.2.7 on 2025-11-14 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0017_vacancy_is_archived'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('name_eng', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='place_of_work',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='work_format',
            field=models.ManyToManyField(to='vacancies.workformat'),
        ),
    ]
