# Generated by Django 5.2.7 on 2025-11-16 14:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0018_workformat_remove_vacancy_place_of_work_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firm',
            name='activity',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='date_published',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата опубликования вакансии'),
        ),
        migrations.AlterField(
            model_name='firm',
            name='address',
            field=models.CharField(max_length=150, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='firm',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
    ]
