# Generated by Django 5.2.7 on 2025-11-16 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0019_remove_firm_activity_vacancy_date_published_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firm',
            name='link',
            field=models.URLField(max_length=100, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='date_published',
            field=models.DateTimeField(verbose_name='Дата опубликования вакансии'),
        ),
    ]
