# Generated by Django 5.2.7 on 2025-11-19 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0020_alter_firm_link_alter_vacancy_date_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='experience',
            field=models.CharField(choices=[('No exp', 'Нет опыта'), ('Year', 'От 1 года до 3 лет'), ('Three years', 'От 3 до 6 лет'), ('Six years', 'Более 6 лет')], default='No exp', verbose_name='Опыт'),
        ),
    ]
