# Generated by Django 5.2.7 on 2026-01-29 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0022_alter_vacancy_experience'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancy',
            old_name='work_format',
            new_name='work_formats',
        ),
    ]
