services:
  backend:
    build: 
      context: ./backend
      dockerfile: DockerFile.backend
    volumes:
      - ./backend/:/back
    env_file: 
      - ./backend/.env.backend
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
  bot:
    build:
      context: ./bot
      dockerfile: DockerFile.bot
    container_name: techhire-bot
    restart: always
    volumes:
      - ./bot/:/bot
    env_file:
      - ./bot/.env.bot
      - ./backend/.env.backend # конфигурация бд для бота
    depends_on:
      - db
      - redis

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./backend/.env.backend
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

  celery:
    build: 
      context: ./backend
      dockerfile: DockerFile.backend
    command: celery -A config worker -l info
    volumes:
      - ./backend/:/back
    env_file:
      - ./backend/.env.backend
    depends_on:
      - redis

  celery-beat:
    build: 
      context: ./backend
      dockerfile: DockerFile.backend
    command: celery -A config beat -l info 
    volumes: 
      - ./backend/:/back
    env_file:
      - ./backend/.env.backend
    depends_on:
      - redis
  
volumes:
  postgres_data:
  redis_data: