# Generated by Django 5.2.7 on 2025-10-20 16:13

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantLinkedTelegram',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('user_id', models.BigIntegerField()),
                ('chat_id', models.BigIntegerField()),
                ('date_linked', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Specializations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Technologies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Почта')),
                ('first_name', models.CharField(max_length=150, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=150, verbose_name='Фамилия')),
                ('city', models.CharField(choices=[('Moscow', 'Москва'), ('Saint Petersburg', 'СПБ')], default='Moscow', verbose_name='Ваш город')),
                ('gender', models.CharField(choices=[('Male', 'Мужской'), ('Female', 'Женский'), ('Not specified', 'Не указан')], default='Male', help_text='Обратите внимание, что не указанный пол может повлиять на построение ваших рекомендаций', verbose_name='Ваш пол')),
                ('age', models.PositiveIntegerField(default=16, validators=[django.core.validators.MinValueValidator(16, message='Ваш возраст должен быть не менее 16 лет.'), django.core.validators.MaxValueValidator(65, message='Ваш возраст должен быть не более 16 лет.')], verbose_name='Ваш возраст')),
                ('experience', models.CharField(choices=[('No exp', 'Без опыта'), ('Year', 'От 1 года'), ('Three years', 'От 3 лет'), ('Six years', 'От 6 лет')], default='No exp', verbose_name='Ваш опыт работы как IT-специалиста')),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('linked_telegram', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.applicantlinkedtelegram')),
                ('specializations', models.ManyToManyField(to='accounts.specializations')),
                ('technologies', models.ManyToManyField(to='accounts.technologies')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
