# Generated by Django 5.2.7 on 2025-10-21 14:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Specializations',
            new_name='Specialization',
        ),
        migrations.RenameModel(
            old_name='Technologies',
            new_name='Technology',
        ),
        migrations.AlterModelOptions(
            name='specialization',
            options={'verbose_name': 'Specialization', 'verbose_name_plural': 'Specializations'},
        ),
        migrations.AlterModelOptions(
            name='technology',
            options={'verbose_name': 'Technology', 'verbose_name_plural': 'Technologies'},
        ),
        migrations.AlterField(
            model_name='applicant',
            name='age',
            field=models.PositiveIntegerField(default=16, validators=[django.core.validators.MinValueValidator(16, message='Ваш возраст должен быть не менее 16 лет.'), django.core.validators.MaxValueValidator(65, message='Ваш возраст должен быть не более 65 лет.')], verbose_name='Ваш возраст'),
        ),
    ]
