# Generated by Django 5.2.7 on 2025-10-21 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_specializations_specialization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='gender',
            field=models.CharField(choices=[('male', 'Мужской'), ('female', 'Женский'), ('not specified', 'Не указан')], default='male', help_text='Обратите внимание, что не указанный пол может повлиять на построение ваших рекомендаций', verbose_name='Ваш пол'),
        ),
    ]
