# Generated by Django 5.2.7 on 2025-10-31 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_applicant_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='gender',
        ),
        migrations.AlterField(
            model_name='applicant',
            name='city',
            field=models.CharField(choices=[('Moscow', 'Москва'), ('Saint Petersburg', 'Санкт-Петербург')], default='Moscow', verbose_name='Ваш город'),
        ),
    ]
