# Generated by Django 5.2.7 on 2025-11-04 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_applicant_gender_alter_applicant_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='experience',
            field=models.CharField(choices=[('No exp', 'Без опыта'), ('Year', 'От 1 года до 3 лет'), ('Three years', 'От 3 до 6 лет'), ('Six years', 'Более 6 лет')], default='No exp', verbose_name='Ваш опыт работы как IT-специалиста'),
        ),
    ]
