# Generated by Django 5.2.7 on 2025-11-27 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_applicant_experience'),
        ('vacancies', '0021_alter_vacancy_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='preferred_work_format',
            field=models.ManyToManyField(to='vacancies.workformat'),
        ),
    ]
