# Generated by Django 5.2.7 on 2025-12-26 06:36

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_specialization_name_alter_technology_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='applicantlinkedtelegram',
            name='username',
        ),
        migrations.AddField(
            model_name='applicant',
            name='username',
            field=models.CharField(default='a', error_messages={'unique': 'Пользователь с таким именем уже существует'}, max_length=32, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='Имя пользователя'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='applicant',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Почта'),
        ),
    ]
