# Generated by Django 5.2.7 on 2025-12-26 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_applicant_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='age',
        ),
        migrations.AddField(
            model_name='applicant',
            name='first_name',
            field=models.CharField(default='a', max_length=64, verbose_name='Имя'),
            preserve_default=False,
        ),
    ]
