# Generated by Django 5.2.7 on 2025-12-26 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_applicant_age_applicant_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantlinkedtelegram',
            name='chat_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
