# Generated by Django 5.2.7 on 2026-01-03 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_applicantlinkedtelegram_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='is_sub',
            field=models.BooleanField(default=False),
        ),
    ]
