# Generated by Django 5.2.7 on 2026-01-06 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_applicant_is_sub'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicant',
            options={'verbose_name': 'Соискатель', 'verbose_name_plural': 'Соискатели'},
        ),
        migrations.AlterModelOptions(
            name='specialization',
            options={'verbose_name': 'Специализация', 'verbose_name_plural': 'Специализации'},
        ),
        migrations.AlterModelOptions(
            name='technology',
            options={'verbose_name': 'Инструмент', 'verbose_name_plural': 'Инструменты'},
        ),
        migrations.AddField(
            model_name='specialization',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='specialization',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='technology',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='technology',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
