# Generated by Django 5.2.7 on 2026-01-06 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_specialization_name_alter_technology_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialization',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='specialization',
            name='is_approved',
        ),
    ]
