# Generated by Django 5.2.7 on 2026-01-08 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_remove_specialization_creator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialization',
            name='id',
            field=models.CharField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='technology',
            name='id',
            field=models.CharField(primary_key=True, serialize=False),
        ),
    ]
