# Generated by Django 5.2.7 on 2026-01-08 17:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_specialization_id_alter_technology_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialization',
            options={'ordering': ['name'], 'verbose_name': 'Специализация', 'verbose_name_plural': 'Специализации'},
        ),
        migrations.AlterModelOptions(
            name='technology',
            options={'ordering': ['name'], 'verbose_name': 'Инструмент', 'verbose_name_plural': 'Инструменты'},
        ),
        migrations.AddField(
            model_name='specialization',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 8, 17, 10, 48, 856470, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='technology',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 8, 17, 10, 48, 856673, tzinfo=datetime.timezone.utc)),
        ),
    ]
