# Generated by Django 5.2.7 on 2026-01-08 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_specialization_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialization',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='technology',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
