# Generated by Django 5.2.7 on 2026-01-20 16:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_specialization_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, error_messages={'invalid': 'That is not a valid UUID format.'}, primary_key=True, serialize=False),
        ),
    ]
