# Generated by Django 5.2.7 on 2026-01-22 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_applicant_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='notifications_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applicantlinkedtelegram',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
