# Generated by Django 5.2.7 on 2026-01-22 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_applicant_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='notifications_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
