# Generated by Django 5.2.7 on 2026-01-25 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_alter_applicant_notifications_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='experience',
            field=models.CharField(choices=[('No exp', 'Нет опыта'), ('Year', 'От 1 года до 3 лет'), ('Three years', 'От 3 до 6 лет'), ('Six years', 'Более 6 лет')], default='No exp', verbose_name='Ваш опыт работы как IT-специалиста'),
        ),
    ]
