# Generated by Django 5.2.7 on 2026-01-29 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_alter_applicant_experience'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicant',
            old_name='preferred_work_format',
            new_name='preferred_work_formats',
        ),
    ]
