# Generated by Django 5.2.7 on 2026-02-02 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_rename_preferred_work_format_applicant_preferred_work_formats'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantlinkedtelegram',
            name='auth_token',
            field=models.CharField(default='default', max_length=40),
            preserve_default=False,
        ),
    ]
