FROM python:3.11-slim

WORKDIR /bot

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN pip install --upgrade pip

COPY requirements_bot.txt /bot/requirements.txt

COPY . /bot/

RUN pip install -r requirements_bot.txt

CMD ["python", "main.py"]